- name : apply local configuration
  hosts: localhost
  become: true

  roles:
          - local

- name : apply the staging servers configuration
  hosts: all
  become: true

  roles:
          - remote