---
  - name: "update packages"
    shell: sudo apt update

  - name: "install curl"
    shell: sudo apt install curl -y

  - name: "run script to update okta uris"
    script: Ansible-CD/oktauris.sh
