---
  - name: "update packages"
    shell: apt update

  - name: "install curl"
    shell: apt install curl -y

  - name: "run script to update okta uris"
    script: oktauris.sh "{{ OKTAURL }}" "{{ OKTACLIENT }}" "{{ OKTAKEY }}" "{{ HOSTIP }}"
