---
      - name: "login to registry"
        shell: docker login -u {{ RUSER }} -p {{ RPASS }} {{ CONTAINERREGISTRY }}
      
      - name: "stop container"
        shell: docker rm -f {{ IMAGEREPOSITORY }} || true

      # - name: "docker pull"
      #   shell: docker pull {{ CONTAINERREGISTRY }}/{{ IMAGEREPOSITORY }}:{{ TAG }} #

      - name: "docker run"
        shell: docker run -d --restart=always --name {{ IMAGEREPOSITORY }} -p 8080:8080 {{ CONTAINERREGISTRY }}/{{ IMAGEREPOSITORY }}:{{ TAG }}
    
      - name: "Template a file"
        template:
          src: './.env'
          dest: '{{ homeDir }}'
          owner: '{{ user }}'
          mode: u=r,g=r,o=r

      - name: "copy env to docker"
        shell: docker cp {{ homeDir }}/.env {{ IMAGEREPOSITORY }}:bootcamp-app\.env

      - name: "docker restart"
        shell: docker restart {{ IMAGEREPOSITORY }}
